version: '3'
services:
 database:
  image: mysql:latest
  container_name: mysqldbprod
  environment:
   - "MYSQL_DATABASE=appdbprod"
   - "MYSQL_USER=appdbprod"
   - "MYSQL_PASSWORD=sd01849sd01849"
   - "MYSQL_ROOT_PASSWORD=sd01849sd01849"
  volumes:
   - db_data:/var/lib/mysql
  ports:
   - "3306:3306"
  networks:
   - mysqldb-network
   
volumes:
 db_data:
 
networks:
  mysqldb-network:
    driver: bridge