version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /nginx/nginx.conf:/etc/nginx/nginx.conf
      - /nginx/html:/html
    environment:
      - NGINX_HOST=kashlab.cc
    networks:
      - webapp_network

